### ISSUE TITLE
Images are not added to the pdf file

### ISSUE THREAD

**Issue by kofe88** [yllen/pdf#12]
Hello. When converting a ticket to a pdf file, images from comments or solutions are not added to the pdf file.
GLPI 9.5.7
Plugin version 2.0.0

---
![image](https://user-images.githubusercontent.com/16879167/158571477-e1f46d43-4931-46b8-b35c-ad2e5baa73b6.png)
---
![image](https://user-images.githubusercontent.com/16879167/158572127-760c15e7-5956-43ce-9842-1b5797962e6a.png)
---
![image](https://user-images.githubusercontent.com/16879167/158572321-c343d406-e877-4075-9ceb-3bf26432b89e.png)

**Comment by yllen** [comment]
same as #5
