### ISSUE TITLE
Generated PDF comes blank

### ISSUE THREAD

**Issue by paulobini1** [yllen/pdf#15]
Hi there, 
I'm running GLPI v9.5.7 on Debian and PHP 7.3.27.
I made an fresh install of PDF plugin on my HOM environment and I'm facing the problem below:

On bulk printing (tickets or assets) the generated PDF comes blank, only showing the page numbers but the body comes empty.
Returning to GLPI central it shows an error notification popup that says "Failed Operation".
On my ../glpi/files/_log/php-errors.log I get the errors below while attemping to generate PDFs:

[2022-05-10 08:51:51] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/pdf/inc/common.class.php at line 373
  Backtrace :
  plugins/pdf/front/export.massive.php:64            PluginPdfCommon->generatePDF()

I already tried to enforce write attributes to the plugin's directory and full permissions to apache user, but the error stands still.

**Comment by yllen** [comment]
Version of plugin used?

**Comment by paulobini1** [comment]
I'm running the current version - 2.0.0

**Comment by yllen** [comment]
No news, i close
