### ISSUE TITLE
Compatibility for GLPI 10

### ISSUE THREAD

**Issue by roshanroche** [yllen/pdf#16]
Hi,

any idea when the GLPI 10 compatible plugin will be released?

**Comment by yllen** [comment]
i'm working on it

**Comment by rafacss** [comment]
> i'm working on it

Thank You!!!

**Comment by ospalope** [comment]
I also thank you Yllen

**Comment by ilicilho** [comment]
I received this errors in GLPI 10.2
PHP Warning (2): include_once(/var/www/glpi/plugins/pdf/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/pdf/setup.php at line 38

**Comment by Hawkiinz** [comment]
Not working for me. Using 2.0.1 on GLPI 1.0.0.
![image](https://user-images.githubusercontent.com/45894451/176695731-6744894b-f335-4d5d-908d-351cb869367f.png)

**Comment by ppasserini** [comment]
> I received this errors in GLPI 10.2 PHP Warning (2): include_once(/var/www/glpi/plugins/pdf/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/pdf/setup.php at line 38

Not very elegant but......just comment out line 38....looks like is working

**Comment by yllen** [comment]
in command line 
in glpi/plugins/pdf
run `composer install`
