### ISSUE TITLE
Mise en page 

### ISSUE THREAD

**Issue by jlb5980** [yllen/pdf#17]
Bonjour
Nous rencontrons un probléme de mise en page suite à impression PDF de réponse à un ticket.
La mise en page en pdf semble ne pas tenir compte des retours à la ligne.

![misenpage1](https://user-images.githubusercontent.com/22024154/173009142-60730720-c7ee-4423-88fc-86979e4a9acc.png)

![miseenpagepdf](https://user-images.githubusercontent.com/22024154/173009168-547d0e41-9a71-4dc0-92ac-a9915cf543f6.png)

Merci d'avance pour vos réponses .
Cordialement

**Comment by yllen** [comment]
fixed https://github.com/yllen/pdf/commit/24332c3a05212ce69e897ea26905cbdf449abb4d
