### ISSUE TITLE
Images in the pdf file are not displayed

### ISSUE THREAD

**Issue by rafacss** [yllen/pdf#19]
I would like to suggest a feature or fix for the PDF plugin. Both in version 9.5 to 10.0.2 of GLPi, the images that are attached in the comments of the tickets are not displayed, I can only see the text of the ticket.

![image](https://user-images.githubusercontent.com/67194670/180649080-4c3bbcde-f7bb-4fea-8159-a1e2f1337852.png)

**Comment by yllen** [comment]
For 9.5 corrected in https://github.com/yllen/pdf/issues/5
For 10 corrected in https://github.com/yllen/pdf/issues/21
