### ISSUE TITLE
Print to PDF Setup problem

### ISSUE THREAD

**Issue by reineken** [yllen/pdf#20]
Hello, when the new print to pdf plugin for GLPI 10.0.0... was released, I also updated my old GLPI to version 10.0.0, because this is the only plugin I needed for GLPI. After updating there are some problems. First of all, PDF plugin is not showing in the new GLPI ''Marketplace'', but that is ok, I imported it manually. Secondly in GLPI Setup menu I cannot edit and configure anything, I can only choose Currency for no reason.
![Screenshot_1](https://user-images.githubusercontent.com/60596345/185060882-cd731216-efe0-4331-88f8-2af6408d969e.png)
I tried this plugin with all of new GLPI 10 versions, every one of them has this problem. Now I am wondering, maybe this is how it is supposed to be and I have to configure PDF layout somewhere else ?
Thank you.

**Comment by yllen** [comment]
It's normal.
- In Setup menu you configure your currency
- In Profile you configure if you allow or not PDF impression
- In your settings you configure the template for massive PDF impression
