### ISSUE TITLE
bad influence to barcode plugin

### ISSUE THREAD

**Issue by gmed-ed** [yllen/pdf#22]
Hi,

actual Version 2.1.0 and the prior Version causes the barcode-plugin to fail:
-> https://github.com/pluginsGLPI/barcode/issues/110

As for now we can only use one of both plugins activated.
If pdf-plugin is same time active with barcode-plugin, the barcode-plugin fails.
Maybe related to the new tcppdf?

Would be kind to get some hints to solve the issue.

**Comment by yllen** [comment]
Unless i am mistaken, barcode use Cezpdf and pdf use tcpdf.
And the error indicated in https://github.com/pluginsGLPI/barcode/issues/110 is that it doesn't fine a function.
When you had install GLPI10, had you create a new directory or had you install it in the current glpi directory?

**Comment by gmed-ed** [comment]
Many thanks for your replay.

We upgraded glpi from 9 to 10 without creating a new folder.
So it may be, that there are some remnants from Version9.

Should I test with clean install of glpi10?
Only copying configs and files folder?


Am 22. September 2022 14:03:50 MESZ schrieb yllen ***@***.***>:
>Unless i am mistaken, barcode use Cezpdf and pdf use tcpdf.
>And the error indicated in https://github.com/pluginsGLPI/barcode/issues/110 is that it doesn't fine a function.
>When you had install GLPI10, had you create a new directory or had you install it in the current glpi directory?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/yllen/pdf/issues/22#issuecomment-1254926645
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 

mit freundlichen Grüßen

Georg Meier

**Comment by yllen** [comment]
In GLPI 9.5 you have tcpdf and in GLPI 10 they use atoum. So you still have a tcpdf of core and a tcpdf of pdf plugin.
I don't know if it's the problem but perhaps.

So, for all major version you must:
- rename the gpli directory to glpiold
- create a new glpi directory
- update it this the new version of glpi
- copy needed files from glpiold to glpi (config_db, all documents...)
