### ISSUE TITLE
insert in the PDF export, a text field

### ISSUE THREAD

**Issue by Jenizarox** [yllen/pdf#25]
Hello friends, can you help me to be able to introduce a fixed text field in this pluginns, I would like to use this plugins to deliver a document **"I hereby state that I received from the company, the following computer equipment, credentials of access to internal systems and cellular equipment for the exclusive use of performing my work activities"**

**Comment by yllen** [comment]
In the configuration of the plugin, under international currency, you can post your own text.
![image](https://user-images.githubusercontent.com/12936722/198659545-fd09b059-8f82-40b3-a1a1-b555ff2fc229.png)

This text will be added at the end of the PDF generation
![image](https://user-images.githubusercontent.com/12936722/198659920-f80ee8dc-d75e-47fd-abbc-3e018198008f.png)
