### ISSUE TITLE
Print error with items

### ISSUE THREAD

**Issue by gkukovacec** [yllen/pdf#28]
Hi,

If ticket has an item attached and I choose to print items, it fails with this error:

**Uncaught Exception TypeError: Argument 1 passed to Toolbox::stripTags() must be of the type string, null given, called in /home/getimin5/public_html/glpi/plugins/pdf/inc/item_ticket.class.php on line 122 in /home/getimin5/public_html/glpi/src/Toolbox.php at line 3109**

Relevant php-errors.log entry:

**[2022-11-02 10:49:48] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Toolbox::stripTags() must be of the type string, null given, called in /home/getimin5/public_html/glpi/plugins/pdf/inc/item_ticket.class.php on line 122 in /home/getimin5/public_html/glpi/src/Toolbox.php at line 3109
  Backtrace :
  plugins/pdf/inc/item_ticket.class.php:122          Toolbox::stripTags()
  plugins/pdf/inc/ticket.class.php:522               PluginPdfItem_Ticket::pdfForTicket()
  plugins/pdf/inc/common.class.php:385               PluginPdfTicket::displayTabContentForPDF()
  plugins/pdf/front/export.php:74                    PluginPdfCommon->generatePDF()**

  
Please help.

Thanks,
Goran

**Comment by yllen** [comment]
duplicate #26
