### ISSUE TITLE
Change GLPI logo 

### ISSUE THREAD

**Issue by phamorais** [yllen/pdf#29]
Change GLPI logo

hi yllen

A proposal to improve the plugin would be to create a field on the plugin's configuration page to allow you to upload an image file to change the original GLPI logo.

It would be possible?

**Comment by RobertoMarcelino** [comment]
To change the logo when generating a PDF report using the PDF plugin (https://github.com/yllen/pdf), you must create two images with the following specifications:

- fd_logo.png in size 100x55 pixels
- fd_logo.jpg in size 61x25 pixels

Copy the two images to the /var/www/html/glpi/marketplace/pdf/pics/ folder.

Copy the fd_logo.png image to the /var/www/html/glpi/pics/ folder.

**Comment by eduardomozart** [comment]
It would be great if the plug-in uses the built-in ``<GLPI_ROOT>/pics/logos/logo-G-100-black.png`` (it has exactly the same width and height) instead of a custom one so replacing the GLPI logo it would automatically reflect at the PDF file export.

**Comment by yllen** [comment]
@eduardomozart the logo you indicated is only a G, not Glpi like in the plugin.

**Comment by eduardomozart** [comment]
@yllen you could use ``<GLPI_ROOT>/pics/logos/logo-GLPI-100-black.png``
