### ISSUE TITLE
Visualization error in tasks with tables

### ISSUE THREAD

**Issue by jussara-ti** [yllen/pdf#34]
Hello!

I discovered a visualization error when generating the pdf.
Tasks containing tables created in GLPI version 10 are partially displayed.
Tables created in GLPI 9 seem to display correctly.
The error appears in version 2.1 and also in version 3 of the pdf plugin.

![error-pdf](https://user-images.githubusercontent.com/60328341/208926026-fbd91d62-1cb3-4751-9f87-730789bff30f.png)

**Comment by yllen** [comment]
OK for you with previous correction?

**Comment by jussara-ti** [comment]
Yes, it worked! The bug has been fixed, thank you very much!

**Comment by yllen** [comment]
Perfect. I close
