### ISSUE TITLE
Problem with special characters in generated PDFs 

### ISSUE THREAD

**Issue by Hantiel** [yllen/pdf#37]
Hi
I have a problem with special characters in generated PDF.
GLPI 10.0.5
Plugin 3.0.0
Language - Polish

Is it possible to edit / add a font that supports special characters ?
![image](https://user-images.githubusercontent.com/113474035/213476889-f8f42521-856e-42c9-a34e-89816b7a9e42.png)

**Comment by yllen** [comment]
I think your issue is like https://github.com/yllen/pdf/issues/8

**Comment by Hantiel** [comment]
Manually changing the variable "$font=helvetica" to a font that supports my language solved the problem - for me "dejavusans
" And this font I have set i GLPI.  

`  $pdf->SetCreator('GLPI');
      $pdf->SetAuthor('GLPI');
      $font       = '**helvetica**';
      //$subsetting = true;
      $fonsize    = 8;
      if (isset($_SESSION['glpipdffont']) && $_SESSION['glpipdffont']) {
         $font       = $_SESSION['glpipdffont'];
         //$subsetting = false;
      }
      $pdf->setHeaderFont(Array($font, 'B', 8));
      $pdf->setFooterFont(Array($font, 'B', 8));`

**Comment by yllen** [comment]
As previously said, you must change the PDF export font in GLPI. This change is for GLPI and for the plugin.
Setup / General / Default values / PDF export font

**Comment by Hantiel** [comment]
> I think your issue is like #8
