### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by sutyagin81** [yllen/pdf#40]
Hello. GLPI 10.0.6 plugin installed but not working. Not visible on the application.
![image](https://user-images.githubusercontent.com/124555902/218942865-0c3fcddb-0ab8-4ec6-8866-76bf488797ee.png)

![image](https://user-images.githubusercontent.com/124555902/218942906-0ef1c030-6c93-4399-b664-e3c744185afa.png)

![image](https://user-images.githubusercontent.com/124555902/218942969-96d493ec-e633-42ba-bdb9-0a258e6b2319.png)

**Comment by yllen** [comment]
Had you give right to print PDF in your profile?

**Comment by yllen** [comment]
No news? i close
