### ISSUE TITLE
Printing with a pdf plugin of the fields of a request, or being able to select a series of fields to print.

### ISSUE THREAD

**Issue by calidadcarm** [yllen/pdf#52]
**PDF Plugin Implementation:**
-----------------------------------

Good morning,

It would be possible or if it will be implemented in the future that the PDF plugin allows the printing of only the fields that we have in a ticket or request.
Or if in your case it is going to be implemented that we can select from all the fields of a ticket those that we want to print.

Thank you.

**Comment by yllen** [comment]
Currently it is possible to print tab by tab.
Modifying the plugin to choose which fields to print in each tab is too much work to do
