### ISSUE TITLE
Deprecated error with php 8.2 and GLPI 10.0.10

### ISSUE THREAD

**Issue by Naosu1** [yllen/pdf#58]
Hello,

Since i updated to 10.0.10, the PDF plugin shows me a "Deprecated" error like

>Deprecated: Creation of dynamic property PluginPdfTicket::$pdf is deprecated in D:\Programs\wamp64\www\glpi\plugins\pdf\inc\common.class.php on line 374
TCPDF ERROR: Some data has already been output, can't send PDF file

>Deprecated: Using ${var} in strings is deprecated, use {$var} instead in D:\Programs\wamp64\www\glpi\plugins\pdf\inc\preference.class.php on line 93

I did a clean reinstallation of the plugin and it's worse... plugin not even installed or activated and I have PHP errors everywhere. Once installed and activated, the dashboard is also filled with php errors.
I carried out a 2nd installation by installing composer in the plugin folder, no more visible errors, but we return to the basic situation whenever i try to export ticket to pdf...

I opened a query on the GLPI community forum and it turns out that it's because my GLPI is running on PHP 8.2 which was pointed out as the cause. In 7.4 everything works, but unfortunately our system admin does not want us to downgrade to 7.4

Is it possible to modify any file(s) to make the plugin compatible with php 8.2?

Thanks in advance

Best regards

**Comment by rginus** [comment]
I solved this by adding **#[AllowDynamicProperties]** just before the line **abstract class PluginPdfCommon extends CommonGLPI {** in the file **.\marketplace\pdf\inc\common.class.php**

**Comment by Naosu1** [comment]
I made the change and now I do not have longer the deprecated errors, however I still have the error

>TCPDF ERROR: Some data has already been output, can't send PDF file

**Comment by Naosu1** [comment]
i solved this from add solution from https://github.com/yllen/pdf/issues/41#issuecomment-1856268929

**Comment by rginus** [comment]
Hi, I got your second Deprecated message when I want to create a PDF of a ticket. Your solution doesn't work for me. I changed line 93 of plugins\pdf\inc\preference.class.php as follows to solve this: 

From: `$formid="plugin_pdf_${type}_".mt_rand();`
To: `$formid="plugin_pdf_{$type}_".mt_rand();`

**Comment by Naosu1** [comment]
Actually I didn't see this above the page.
![image](https://github.com/yllen/pdf/assets/53087995/be8634af-f1ba-46d0-9054-ff03c6bf773d)

with online patch 93 I no longer have the problem either, thank you

**Comment by yllen** [comment]
Already corrected in November: https://github.com/yllen/pdf/commit/bddedfb7e576a5ce8959706179f1b051cf9e6711
Duplicate https://github.com/yllen/pdf/issues/54
