### ISSUE TITLE
Error while exporting tickets via massive action and the plugin sources are int the marketplace folder 

### ISSUE THREAD

**Issue by EORIS-SUPPORT** [yllen/pdf#70]
Hello 

I've installed the PDF plugin via the marketplace web interface , which means that it is located in /glpi/marketplace/ folder

when I try to export a ticket via the massive actions, the URL is pointing to http://localhost/10.0.15/plugins/pdf/front/export.massive.php which result in a 404 error , if i replace "plugins" by "marketplace" in the URL I manage to obtain a PDF of my ticket . 

it seems that the fact that the PDF plugins is installed in the "plugins" folder is hardcoded in the plugin , could it be possible to correct that please ?

**Comment by BenLasTed** [comment]
Exact same issue here. Is anyone has resolved this bug?

Edit: Seems to be fixed with this https://github.com/yllen/pdf/commit/af218fd92e8346dac8a30ed841501081704eefa2

**Comment by yllen** [comment]
already corrected
